CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 accelerate launch --multi_gpu --num_processes=8 train_vae.py \
  --pretrained_model_name_or_path="./sd-vae-ft-mse" \
  --image_column=img \
  --validation_images val_imgs/004337008.jpg \
  --resolution=512 \
  --train_batch_size=4 \
  --gradient_accumulation_steps=24 \
  --use_ema \
  --train_data_dir="imagefolder" \
  --image_column="image" \
  --report_to="tensorboard"
